#ifndef WN_NR_PHY_GNB_RE_DE_MAPPER_H
#define WN_NR_PHY_GNB_RE_DE_MAPPER_H
#include "wnNrPhygNBUlChnlConfigInit.h"

cmplx reDemapperIn[MAX_SUMIMO_PUSCH_ANTENNA_PORTS][NUMBER_OF_OFDM_SYMBOLS_SLOT][MAX_SUB_CARRIERS_OFDM_SYMBOL];

#endif